server:
  port: 8080

general:
  default_locale: en

spring:
  application:
    name: reservation

  datasource:
    url: jdbc:mysql://localhost:3306/reservation?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 50
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
        default_batch_fetch_size: 30
        enable_lazy_load_no_trans: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false

jwt:
  secret: dvd25vQuuiPZvi46advjewu
  token_validity_in_minutes: 120  # 2 * 60
  refresh_token_validity_in_minutes: 1440 # 24 * 60

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config

logging:
  level:
    org:
      springframework:
        web: DEBUG